<?php include 'header.php'; ?>
<?php 
include 'db.php'; 
// In a real app, these would be generated by SQL queries based on $_GET filters
$report_type = $_GET['type'] ?? 'inventory';
?>

<div class="p-8 overflow-y-auto w-full h-full bg-slate-50">
    <header class="flex justify-between items-end mb-10">
        <div>
            <h2 class="text-3xl font-black text-slate-900 tracking-tight">Business Intelligence Reports</h2>
            <p class="text-xs text-slate-400 font-bold uppercase tracking-widest mt-1">Exportable Data & Performance Metrics</p>
        </div>
        <div class="flex gap-2">
            <button class="px-6 py-3 bg-emerald-500 text-white rounded-2xl text-[10px] font-black uppercase tracking-widest shadow-xl shadow-emerald-500/20 hover:bg-emerald-600 transition-all flex items-center gap-2">
                <i data-lucide="download" class="w-4 h-4"></i> Export PDF
            </button>
        </div>
    </header>

    <!-- Filters -->
    <div class="bg-white p-6 rounded-[32px] border border-slate-200 shadow-sm mb-8 flex flex-wrap items-end gap-4">
        <div class="space-y-1.5 flex-1 min-w-[200px]">
            <label class="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">Report Category</label>
            <form method="GET" action="reports.php">
                <select name="type" onchange="this.form.submit()" class="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 text-xs font-bold outline-none focus:ring-4 focus:ring-emerald-500/10">
                    <option value="inventory" <?php echo $report_type == 'inventory' ? 'selected' : ''; ?>>Inventory Audit</option>
                    <option value="sales" <?php echo $report_type == 'sales' ? 'selected' : ''; ?>>Sales Performance</option>
                    <option value="staff" <?php echo $report_type == 'staff' ? 'selected' : ''; ?>>Staff Productivity</option>
                </select>
            </form>
        </div>
        <div class="space-y-1.5 flex-1 min-w-[200px]">
            <label class="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">Date Range</label>
            <div class="flex gap-2">
                <input type="date" class="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 text-xs font-bold" value="<?php echo date('Y-m-d'); ?>">
                <input type="date" class="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 text-xs font-bold" value="<?php echo date('Y-m-d'); ?>">
            </div>
        </div>
        <button class="px-8 py-3 bg-slate-900 text-white rounded-xl text-[10px] font-black uppercase tracking-widest hover:bg-black transition-all">Generate</button>
    </div>

    <!-- Report Table -->
    <div class="bg-white rounded-[32px] border border-slate-200 shadow-sm overflow-hidden">
        <div class="p-8 border-b border-slate-50 bg-slate-50/30 flex justify-between items-center">
            <h3 class="text-xs font-black text-slate-900 uppercase tracking-widest">
                <?php echo strtoupper($report_type); ?> DATA STREAM
            </h3>
            <span class="text-[9px] font-black text-slate-400 uppercase tracking-widest">Generated: <?php echo date('M d, Y h:i A'); ?></span>
        </div>
        <div class="overflow-x-auto">
            <?php if($report_type == 'inventory'): ?>
            <table class="w-full text-left">
                <thead class="bg-slate-50 text-[9px] font-black text-slate-400 uppercase tracking-widest">
                    <tr>
                        <th class="px-8 py-4">Item Name</th>
                        <th class="px-6 py-4">Current Stock</th>
                        <th class="px-6 py-4">Unit Cost</th>
                        <th class="px-6 py-4">Valuation</th>
                        <th class="px-8 py-4 text-right">Health Status</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-slate-50 text-xs font-bold">
                    <tr>
                        <td class="px-8 py-5 text-slate-900">Wireless Mouse Pro</td>
                        <td class="px-6 py-5">15 pcs</td>
                        <td class="px-6 py-5">₱25.00</td>
                        <td class="px-6 py-5">₱375.00</td>
                        <td class="px-8 py-5 text-right"><span class="text-emerald-500">GOOD</span></td>
                    </tr>
                </tbody>
            </table>
            <?php else: ?>
            <div class="p-20 text-center text-slate-300">
                <i data-lucide="bar-chart-3" class="w-12 h-12 mx-auto mb-4 opacity-20"></i>
                <p class="text-[10px] font-black uppercase tracking-widest">Aggregating historical telemetry data...</p>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>

<?php include 'footer.php'; ?>
